[package]
name = "xidown"
version = "0.1.0"
edition = "2021"

[dependencies]
biliup = "0.1.11"
curl = "0.4.46"
reqwest = { version = "0.12.2", features = ["blocking"] }
serde = "1.0.204"
serde_json = "1.0.120"
tokio = "1.38.1"
url = "2.5.2"
zeroize = "1.4.3"
